# freeipa-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-data
  namespace: freeipa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-legolas-jh