# lldap-tls.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lldap-selfsigned
spec:
  selfSigned: {}
---
# This Certificate generates a CA keypair in secret lldap-ca
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-ca
  namespace: lldap
spec:
  isCA: true
  commonName: lldap-internal-ca
  secretName: lldap-ca
  issuerRef:
    name: lldap-selfsigned
    kind: ClusterIssuer
---
# This Issuer uses that CA to sign leaf certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: lldap-ca-issuer
  namespace: lldap
spec:
  ca:
    secretName: lldap-ca
---
# Leaf cert for the LLDAP Service DNS names
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-server
  namespace: lldap
spec:
  secretName: lldap-server-tls
  issuerRef:
    name: lldap-ca-issuer
    kind: Issuer
  dnsNames:
    - lldap
    - lldap.lldap
    - lldap.lldap.svc
    - lldap.lldap.svc.cluster.local
  usages:
    - digital signature
    - key encipherment
    - server auth