---
apiVersion: v1
kind: Namespace
metadata:
  name: lldap

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: lldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

---
# Secret is NOT defined here - apply it manually (see secrets/README.md)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
  labels:
    app: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      labels:
        app: lldap
    spec:
      containers:
        - name: lldap
          image: lldap/lldap:stable
          ports:
            - name: ldap
              containerPort: 3890
            - name: webui
              containerPort: 17170
          env:
            - name: LLDAP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lldap-secret
                  key: LLDAP_JWT_SECRET
            - name: LLDAP_LDAP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: lldap-secret
                  key: LLDAP_LDAP_USER_PASS
            - name: LLDAP_LDAP_BASE_DN
              value: "dc=cluster,dc=local"
            - name: LLDAP_LDAP_USER_DN
              value: "admin"
            - name: LLDAP_HTTP_URL
              value: "http://localhost:17170"
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 3890
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lldap-data

---
apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
spec:
  selector:
    app: lldap
  ports:
    - name: ldap
      port: 3890
      targetPort: 3890
    - name: webui
      port: 17170
      targetPort: 17170
