[sssd]
services = nss, pam, ssh
domains = cluster.local
config_file_version = 2

[domain/cluster.local]
id_provider = ldap
auth_provider = ldap
ldap_id_use_start_tls = false
ldap_uri = ldaps://lldap.lldap.svc.cluster.local:6360
ldap_tls_reqcert = demand
ldap_tls_cacert = /etc/ssl/certs/lldap-ca.crt
ldap_search_base = dc=cluster,dc=local
ldap_user_search_base = ou=people,dc=cluster,dc=local
ldap_group_search_base = ou=groups,dc=cluster,dc=local

# bind user
ldap_default_bind_dn = uid=sssd,ou=people,dc=cluster,dc=local
ldap_default_authtok_type = password
ldap_default_authtok = SSSD_BIND_PASSWORD_PLACEHOLDER

# user info
ldap_user_object_class = posixAccount
ldap_user_name = uid
ldap_user_uid_number = uidNumber
ldap_user_gid_number = gidNumber
fallback_homedir = /home/%u
default_shell = /bin/bash

# group info
ldap_schema = rfc2307bis
ldap_group_object_class = groupOfUniqueNames
ldap_group_member = uniqueMember
ldap_group_name = cn

cache_credentials = true
enumerate = true
entry_cache_timeout = 300