# davyjones-shared.yaml
---
# davyjones sc
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-davyjones-hdd
provisioner: nfs.csi.k8s.io
volumeBindingMode: Immediate

---
# shared pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-davyjones-shared
spec:
  capacity:
    storage: 500Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-davyjones-hdd
  mountOptions:
    - hard
  nfs:
    server: davyjones.scripps.edu
    path: /davyjones_data_zfspool/brineylab_shared

---
# shared pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-davyjones-shared
  namespace: slurm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-davyjones-hdd
  volumeName: nfs-davyjones-shared
  resources:
    requests:
      storage: 500Ti
