apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-homes
  namespace: slurm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-legolas-jh
  resources:
    requests:
      storage: 100Gi