# stringer-ont.yaml
---
# stringer sc
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-stringer-hdd
provisioner: nfs.csi.k8s.io
volumeBindingMode: Immediate

---
# ont pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stringer-ont
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-stringer-hdd
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: stringer.scripps.edu
    path: "/volume1/ONT"

---
# ont pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-stringer-ont
  namespace: slurm
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-stringer-hdd
  volumeName: nfs-stringer-ont
  resources:
    requests:
      storage: 100Ti